### ISSUE TITLE
Estructura orgánica del PODER EJECUTIVO NACIONAL + Nómina de Autoridades Superiores

### ISSUE THREAD

**Issue by carohadad** [datosgobar/datasets-portal#1]
- [ ] Data Raw
- [x] Limpieza
- [x] Subir script de limpieza
- [x] Metadata básica
- [x] Readme

**Comment by meliascosta** [comment]
Todavia no esta la data posta asi que hay que volver a hacer una pasada sobre todo despues.

**Comment by meliascosta** [comment]
Tambien hay que reescribir el script de limpieza con la nueva interfaz de la libreria cleaner. DONE

**Comment by abenassi** [comment]
Aunque vos no reescribas el script que usaste ponelo en el repo de
_datasets-portal_, así vamos arrancando. Simplemente especificá en un
comment / docstring al principio del .py con qué versión de data-cleaner se
aplican esas reglas (ie. 0.1.7, la 0.1.8 es la nueva)

2016-02-23 12:20 GMT-03:00 Martin Elias Costa notifications@github.com:

**Comment by meliascosta** [comment]
Subida la nueva version
