### ISSUE TITLE
Acceso a la Informacion

### ISSUE THREAD

**Issue by nsampi** [datosgobar/datasets-portal#12]
Esta es la carpeta, con info para la metadata:

https://drive.google.com/open?id=0B-0OMNhno-_TWEY0Y1NlNEJXcDA
- [X] Data Raw
- [ ] Limpieza
- [ ] Subir script de limpieza
- [ ] Metadata básica
- [ ] Readme

**Comment by carohadad** [comment]
Borrar registros año 2010.

**Comment by chadad** [comment]
Sacar Columna de Razón Social
