### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#17]
Hola, felicitaciones por el lanzamiento del portal.
Solicito que se defina un texto de licencia para el contenido de este repositorio, de forma que quede establecido los términos en los que está publicado, si existe un propietario de los derechos de copia, los requisitos para reutilizar y redistribuir el contenido aquí presentado, como por ejemplo la necesidad de hacer referencia a los autores originales o de distribuirlo con la misma licencia.

Sugiero utilizar una licencia aprobada por la OSI.

**Comment by abenassi** [comment]
Gracias @martinszy por tu comentario, que me parece muy pertinente. Vamos a estar hablando de este tema con el equipo para tomar una definición!

**Comment by vlasvlasvlas** [comment]
+1

**Comment by martinszy** [comment]
Leí la licencia, dice que el titular del copyright es "Gobierno Abierto Argentina" ... eso es una entidad legal? Es necesario que lo sea? perdón, pero no soy abogado, sólo pregunto.

Otra cosa serían las razones por las que elijen estos términos en la licencia y no otros, si tienen ganas de explicarlo.
Algunos repositorios ya eran GPL y ahora tienen dos licencias, no creo que sea un problema pero parece redundante.
Hay algua razón para eso?

**Comment by vlasvlasvlas** [comment]
CC BY ? https://creativecommons.org/licenses/by/2.0/
