### ISSUE TITLE
Dataset: Acceso a la información. Error: Fecha en el futuro.

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#19]
Revisando el dataset de acceso a la información descubrí una fecha en el futuro.

Archivo: http://datos.gob.ar/dataset/8bc053c8-efc2-485d-97d3-915c476d2741/resource/63952097-cdba-4fdd-be84-65fb400bdb1a/download/acceso-informacion-publica.csv
Fila: 19
Expediente: EXP-S04:55469/15
isodatetime_fecha_de_recepcion_de_la_solicitud_por_el_enlace: 2016-10-07T00:00:00-03:00
fecha_de_recepcion_de_la_solicitud_por_el_enlace: 10/7/2016

**Comment by carohadad** [comment]
Gracias! Se lo vamos a comunicar al área. Te avisamos lo que responden por acá.

**Comment by meliascosta** [comment]
Faltaria cambiar el formato de la columna id para que salga como un int en lugar de un float.

**Comment by nsampi** [comment]
Gracias por el comentario @martinszy! Acudimos al área responsable, que revisó nuevamente los datos y subimos la [versión actualizada](http://www.datos.gob.ar/dataset/solicitudes-acceso-informacion-publica/archivo/63952097-cdba-4fdd-be84-65fb400bdb1a) de la información.

Con esto corregimos el issue #22 también.
