### ISSUE TITLE
Traduccion en explorador de datos

### ISSUE THREAD

**Issue by damcasti** [datosgobar/datasets-portal#20]
Felicitaciones gente por el desarrollo! 
Estaría bueno que no queden cosas en ingles, como la parte de búsqueda en los visualizadores de datos, cantidad de registros y botones.

ejemplo:

http://www.datos.gob.ar/dataset/ejecucion-presupuestaria-de-la-administracion-publica-nacional/archivo/84e23782-7d52-4724-a4ba-2f9621fa5f4e?view_id=fbeba5a0-fd21-4d3b-b1f1-bd6697130a2d

saludos! :)

**Comment by martinszy** [comment]
Estoy de acuerdo con este reporte, hay cosas en inglés, lo que dificulta el
acceso a estas herramientas para algunos usuarios, y potencialmente sería
una violación de la ley de accesibilidad web.
Agregaría que, de todas formas, estas herramientas de graficación no
resultan demasiado útiles.

**Comment by iheredia** [comment]
Buenas, 

Esta dentro del desarrollo pendiente. Como el portal nació de un fork de ckan quedaron un par de cosas sin traducir. Proximamente subiremos mas cambios para lograr una mejor experiencia. 

Pueden seguir el desarrollo del sitio en el repo correspondiente: https://github.com/gobabiertoAR/ckanext-gobar_theme

Cualquier otra sugerencia es bienvenida (:

**Comment by damcasti** [comment]
Excelente! data.buenosaires.gob.ar tbn posee cosas así ahora que lo veo :/

**Comment by vlasvlasvlas** [comment]
sepes. el ckan de gcba tmb tiene estas cosas.. dami había otras que habiamos encontrado no? en gcba ckan para reportar..

**Comment by martinszy** [comment]
Creo que este issue va en el repo del ckan, no acá. Sugiero cerrarlo y
abrirlo de nuevo allá.

**Comment by iheredia** [comment]
Aclaro que el portal de datos de la ciudad de buenos aires pertenece a otra dependencia. Esta organización de github - github.com/gobabiertoAR - maneja temas relacionados al gob de la nación.
