### ISSUE TITLE
Dataset: Estructura orgánica. Error: Piso "nan"

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#21]
Dataset: http://datos.gob.ar/dataset/estructura-organica-pen/archivo/b705d8c1-650f-43cc-bde6-68850fcecd21
Linea: 8
Piso: "nan"

Asumo que nan significa "not a number" un error de parseo a la hora de interpretar el piso como un número.

**Comment by abenassi** [comment]
Gracias Martin, efectivamente significa eso. Hoy lo revisamos y lo
corregimos!

**Comment by abenassi** [comment]
@nsampi , te paso este tema que ya está dentro de tu scope. Cualquier duda decime!

**Comment by nsampi** [comment]
@martinszy ya subimos el [dataset corregido](http://www.datos.gob.ar/dataset/estructura-organica-pen/archivo/b705d8c1-650f-43cc-bde6-68850fcecd21).

**Comment by martinszy** [comment]
Ahora no es más la línea 8, tiene el id 83.
¿Reasignaron los IDs?
Podría traer problemas si cada vez que se publica el dataset se reordenan los registros y se reasigan los IDs.

Yo no había descargado la versión anterior de este, pero ahora me gustaría verla y veo que en el sitio no está.
¿Qué opinan de que cuando un dataset se actualiza quede la versión vieja como referencia?
