### ISSUE TITLE
Dataset: Acceso a la información. ¿Más filas?

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#22]
En la versión del 7 de Marzo de este dataset había 400 filas, ahora hay 1200, aproximadamente. ¿Qué ocurrió?
En ningún lugar se explica por qué este dataset podría crecer.

**Comment by nsampi** [comment]
Gracias por el aviso @martinszy. Al subir al portal se triplicaron las lineas y por eso la diferencia de una fecha a la otra. 

Al descargar el archivo .csv se puede ver que el original se mantiene en el orden de las 400 lineas. Durante el día vamos a estar resolviendo el problema con la pre-visualización.

**Comment by nsampi** [comment]
Corregido!

**Comment by martinszy** [comment]
Chicos esto está muy confuso.
Explorador: 168 filas.
Tabla: 1422 filas.
CSV: 419 filas.
ID: 330 (hay varios ID duplicados en el CSV)

Además veo algo raro en el diseño del explorador, hay dos barras de scroll.

**Comment by nsampi** [comment]
Revisar datastore y duplicación de registros.

**Comment by nsampi** [comment]
@martinszy los registros son efectivamente 418 más una linea de cabecera. Es decir son 320 pedidos con 418 casos. 

En cuanto a la tabla y el explorador efectivamente esta duplicando registros. 

Gracias por avisar!
