### ISSUE TITLE
Dataset: Acceso a la información. ¿Id = casos?

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#23]
Parece que id, pedidos y casos son el mismo número
Ejemplo: http://i.imgur.com/AxAvU4U.png

¿Es sólo una apariencia causada por el orden de la tabla o hay realmente un error de procesamiento?

Insisto en que sería genial tener los archivos crudos #18 para detectar si estos son errores de procesamiento, y dejar publicadas las versiones anteriores como sugería en este comentario https://github.com/gobabiertoAR/datasets-portal/issues/21#issuecomment-195107168 para poder comparar y entender los cambios.

**Comment by nsampi** [comment]
Son tres campos distintos. 

El campo "**_id**" es un campo incremental autogenerado por el plugin que se utiliza para pre visualizar los datos en ckan. A partir del comentario al issue #21 entendemos que es confuso, mismo porque es un campo que no figura en los archivos .csv originales. Estamos evaluando una solución para eso.

Los campos "**pedidos**" y "**casos**" son diferentes, coinciden en la numeración hasta el pedido 24 pero luego a medida que un pedido implica mas casos se desacopla la numeración ([documentación](https://github.com/gobabiertoAR/datasets-portal/blob/master/acceso-a-la-informacion/acceso-a-la-informacion.md)).

Avísanos cualquier cosa.
