### ISSUE TITLE
Descarga dataset SIPRO

### ISSUE THREAD

**Issue by martinszy** [datosgobar/datasets-portal#25]
Hola, el dataset SIPRO da un error durante la previsualización

URL: http://datos.gob.ar/dataset/sistema-de-contrataciones-electronicas-argentina-compra/archivo/c19a2467-5232-41ae-bb0c-75dcd71e7c5f#

Error:

> Could not load view: DataProxy returned an error (Data transformation failed. HTTPException: Deadline exceeded while waiting for HTTP response from URL: http://datos.gob.ar/dataset/069b5833-e57d-4d7a-859b-67a80cfdff20/resource/c19a2467-5232-41ae-bb0c-75dcd71e7c5f/download/proveedores-sipro.csv)

Además el botón "Descargar recurso" presente en la página sólo recarga la página.

La única forma de descargar el recurso es hacer click en una flecha gris, casi invisible para la mayoría de los usuarios.

Abrazo!

**Comment by pilimayora** [comment]
Hola @martinszy !

Cuando levantaste este issue estábamos justo planificando una migración del portal para evitar este tipo de problemas y se nos pasó de largo tu issue, perdón! Este problema no debería ocurrir más. Nos confirmás que podés acceder al recurso sin problemas, por favor?

Muchas gracias atrasadas por levantar el issue y prometemos responder más rápido la próxima ;)
Abrazo!
