### ISSUE TITLE
Establecimientos Educativos

### ISSUE THREAD

**Issue by carohadad** [datosgobar/datasets-portal#3]
- [x] Data Raw
- [ ] Limpieza
- [ ] Subir script de limpieza
- [ ] Metadata básica
- [ ] Readme

**Comment by vlasvlasvlas** [comment]
Hola!

Laburo en Ministerio de Energía y Minería, y para nuestro SIG (sig.se.gob.ar) estuvimos corrigiendo puntos geo de establecimientos educativos del Ministerio de educación, ya que encontramos muchos que caian mal.. 

Podemos contarles qué estuvimos haciendo para corregirlos.
salutes!
Vladi Bellini
Tecnología de la información,
Ministerio de Energía y Minería.

**Comment by damcasti** [comment]
Tal cual! ademas hay mucha info que se puede sumar de sig.se.gob.ar

**Comment by gonzaloiglesias** [comment]
Gracias @vlasvlasvlas por la ayuda, contamos con eso. Y btw, tremendo trabajo el de sig.se.gob.ar
Establecimientos Educativos es uno de esos datasets "angulares", por la cantidad de usos colaterales que generó en estos años, particularmente para los que trabajan temas electorales. Tenemos mucho, mucho para charlar con el equipo de Mapa Educativo.

**Comment by carohadad** [comment]
Muchas gracias Vlas y Dami. Cerramos este issue y seguimos conversando.
